/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCheckinRouteImport } from './routes/api/checkin'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiInsightsRouteImport } from './routes/api/insights'
import { Route as ApiMemoriesRouteImport } from './routes/api/memories'
import { Route as ApiProfilesRouteImport } from './routes/api/profiles'
import { Route as ApiSeedWalrusRouteImport } from './routes/api/seed-walrus'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckinRoute = ApiCheckinRouteImport.update({
  id: '/api/checkin',
  path: '/api/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInsightsRoute = ApiInsightsRouteImport.update({
  id: '/api/insights',
  path: '/api/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoriesRoute = ApiMemoriesRouteImport.update({
  id: '/api/memories',
  path: '/api/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesRoute = ApiProfilesRouteImport.update({
  id: '/api/profiles',
  path: '/api/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedWalrusRoute = ApiSeedWalrusRouteImport.update({
  id: '/api/seed-walrus',
  path: '/api/seed-walrus',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/checkin': typeof ApiCheckinRoute
  '/api/health': typeof ApiHealthRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/memories': typeof ApiMemoriesRoute
  '/api/profiles': typeof ApiProfilesRoute
  '/api/seed-walrus': typeof ApiSeedWalrusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/checkin': typeof ApiCheckinRoute
  '/api/health': typeof ApiHealthRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/memories': typeof ApiMemoriesRoute
  '/api/profiles': typeof ApiProfilesRoute
  '/api/seed-walrus': typeof ApiSeedWalrusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/checkin': typeof ApiCheckinRoute
  '/api/health': typeof ApiHealthRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/memories': typeof ApiMemoriesRoute
  '/api/profiles': typeof ApiProfilesRoute
  '/api/seed-walrus': typeof ApiSeedWalrusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/checkin'
    | '/api/health'
    | '/api/insights'
    | '/api/memories'
    | '/api/profiles'
    | '/api/seed-walrus'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/checkin'
    | '/api/health'
    | '/api/insights'
    | '/api/memories'
    | '/api/profiles'
    | '/api/seed-walrus'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/checkin'
    | '/api/health'
    | '/api/insights'
    | '/api/memories'
    | '/api/profiles'
    | '/api/seed-walrus'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCheckinRoute: typeof ApiCheckinRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiInsightsRoute: typeof ApiInsightsRoute
  ApiMemoriesRoute: typeof ApiMemoriesRoute
  ApiProfilesRoute: typeof ApiProfilesRoute
  ApiSeedWalrusRoute: typeof ApiSeedWalrusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkin': {
      id: '/api/checkin'
      path: '/api/checkin'
      fullPath: '/api/checkin'
      preLoaderRoute: typeof ApiCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/insights': {
      id: '/api/insights'
      path: '/api/insights'
      fullPath: '/api/insights'
      preLoaderRoute: typeof ApiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memories': {
      id: '/api/memories'
      path: '/api/memories'
      fullPath: '/api/memories'
      preLoaderRoute: typeof ApiMemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles': {
      id: '/api/profiles'
      path: '/api/profiles'
      fullPath: '/api/profiles'
      preLoaderRoute: typeof ApiProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed-walrus': {
      id: '/api/seed-walrus'
      path: '/api/seed-walrus'
      fullPath: '/api/seed-walrus'
      preLoaderRoute: typeof ApiSeedWalrusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCheckinRoute: ApiCheckinRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiInsightsRoute: ApiInsightsRoute,
  ApiMemoriesRoute: ApiMemoriesRoute,
  ApiProfilesRoute: ApiProfilesRoute,
  ApiSeedWalrusRoute: ApiSeedWalrusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
